# Generated by Django 4.0.5 on 2022-09-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateGodown',
        ),
    ]
