# Generated by Django 4.0.5 on 2022-09-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_creategodown'),
    ]

    operations = [
        migrations.CreateModel(
            name='countrymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='groupanalysismodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perticular', models.CharField(max_length=250)),
                ('pquatity', models.IntegerField()),
                ('prate', models.IntegerField()),
                ('pvalue', models.IntegerField()),
                ('squatity', models.IntegerField()),
                ('srate', models.IntegerField()),
                ('svalue', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='groupcreatemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=250)),
                ('galias', models.CharField(max_length=250)),
                ('gunder', models.CharField(max_length=250)),
                ('gbehaves', models.CharField(max_length=250)),
                ('gallocate', models.CharField(max_length=250)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='ledgeranalysismodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lperticular', models.CharField(max_length=250)),
                ('lpquatity', models.IntegerField()),
                ('lprate', models.IntegerField()),
                ('lpvalue', models.IntegerField()),
                ('lsquatity', models.IntegerField()),
                ('lsrate', models.IntegerField()),
                ('svalue', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='ledgercreatemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=250)),
                ('lalias', models.CharField(max_length=250)),
                ('lunder', models.CharField(max_length=250)),
                ('lmname', models.CharField(max_length=250)),
                ('laddress', models.CharField(max_length=250)),
                ('lstate', models.CharField(max_length=250)),
                ('lcountry', models.CharField(max_length=250)),
                ('lpincode', models.CharField(max_length=250)),
                ('lbank', models.CharField(max_length=250)),
                ('lpan', models.CharField(max_length=250)),
                ('lreg', models.CharField(max_length=250)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='statemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.countrymodel')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='salevouchermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('basicrate', models.IntegerField()),
                ('basicvalue', models.IntegerField()),
                ('addlcost', models.IntegerField()),
                ('totalvalue', models.IntegerField()),
                ('efsrate', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('stockitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.groupanalysismodel')),
                ('udergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.groupcreatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='salesledgervouchermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldate', models.DateField(auto_now_add=True)),
                ('lname', models.CharField(max_length=250)),
                ('lquantity', models.IntegerField()),
                ('lbasicrate', models.IntegerField()),
                ('lbasicvalue', models.IntegerField()),
                ('laddlcost', models.IntegerField()),
                ('ltotalvalue', models.IntegerField()),
                ('lefsrate', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('lstockitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ledgeranalysismodel')),
                ('ludergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='purchasevouchermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('basicrate', models.IntegerField()),
                ('basicvalue', models.IntegerField()),
                ('addlcost', models.IntegerField()),
                ('totalvalue', models.IntegerField()),
                ('efsrate', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('stockitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.groupanalysismodel')),
                ('udergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.groupcreatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='purchaseledgervouchermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldate', models.DateField(auto_now_add=True)),
                ('lname', models.CharField(max_length=250)),
                ('lquantity', models.IntegerField()),
                ('lbasicrate', models.IntegerField()),
                ('lbasicvalue', models.IntegerField()),
                ('laddlcost', models.IntegerField()),
                ('ltotalvalue', models.IntegerField()),
                ('lefsrate', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('lstockitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ledgeranalysismodel')),
                ('ludergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreatemodel')),
            ],
        ),
        migrations.AddField(
            model_name='ledgeranalysismodel',
            name='lpert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreatemodel'),
        ),
        migrations.AddField(
            model_name='groupanalysismodel',
            name='pert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.groupcreatemodel'),
        ),
    ]
