# Generated by Django 4.0.4 on 2022-09-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_countrymodel_groupanalysismodel_groupcreatemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('period', models.CharField(blank=True, default='null', max_length=225)),
                ('units', models.CharField(blank=True, default='null', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Create_employeegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('define_salary', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='create_payhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('pay_type', models.CharField(max_length=225)),
                ('income_type', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('affect_net', models.CharField(max_length=225)),
                ('payslip', models.CharField(max_length=225)),
                ('calculation_of_gratuity', models.CharField(max_length=225)),
                ('cal_type', models.CharField(max_length=225)),
                ('calculation_period', models.CharField(max_length=225)),
                ('leave_withpay', models.CharField(max_length=225)),
                ('leave_with_out_pay', models.CharField(max_length=225)),
                ('production_type', models.CharField(max_length=225)),
                ('opening_balance', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='create_VoucherModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('abbreviation', models.CharField(max_length=225)),
                ('active_this_voucher_type', models.CharField(max_length=225)),
                ('method_voucher_numbering', models.CharField(max_length=225)),
                ('use_adv_conf', models.CharField(blank=True, max_length=225)),
                ('prvnt_duplictes', models.CharField(blank=True, default='Null', max_length=225)),
                ('use_effective_date', models.CharField(default='Null', max_length=225)),
                ('allow_zero_value_trns', models.CharField(max_length=225)),
                ('allow_naration_in_voucher', models.CharField(max_length=225)),
                ('make_optional', models.CharField(max_length=225)),
                ('provide_naration', models.CharField(max_length=225)),
                ('print_voucher', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='emp_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=225)),
                ('cat_alias', models.CharField(max_length=225)),
                ('revenue_items', models.CharField(max_length=225)),
                ('non_revenue_items', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('date_join', models.DateField()),
                ('defn_sal', models.CharField(max_length=225)),
                ('emp_name', models.CharField(max_length=225)),
                ('emp_desg', models.CharField(max_length=225)),
                ('fnctn', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('dob', models.DateField()),
                ('blood', models.CharField(max_length=225)),
                ('parent_name', models.CharField(max_length=225)),
                ('spouse_name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('number', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('inc_tax_no', models.CharField(max_length=225)),
                ('aadhar_no', models.CharField(max_length=225)),
                ('uan', models.CharField(max_length=225)),
                ('pfn', models.CharField(max_length=225)),
                ('pran', models.CharField(max_length=225)),
                ('esin', models.CharField(max_length=225)),
                ('bankdtls', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('effective', models.CharField(max_length=225)),
                ('payhead', models.CharField(max_length=225)),
                ('rate', models.CharField(max_length=225)),
                ('per', models.CharField(max_length=225)),
                ('pay_type', models.CharField(max_length=225)),
                ('cal_type', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=225)),
                ('symbol', models.CharField(max_length=225)),
                ('formal_name', models.CharField(max_length=225)),
                ('uqc1', models.CharField(blank=True, default='null', max_length=225)),
                ('number_of_decimal_places', models.CharField(max_length=225)),
                ('first_unit', models.CharField(max_length=225)),
                ('conversion', models.CharField(max_length=225)),
                ('second_unit', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='uqc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_uqc', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Rounding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rounding_Method', models.CharField(blank=True, default='Null', max_length=225)),
                ('Round_limit', models.CharField(blank=True, default='Null', max_length=22)),
                ('pay_head_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.create_payhead')),
            ],
        ),
        migrations.CreateModel(
            name='gratuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_months', models.CharField(max_length=225)),
                ('number_of_months_from', models.CharField(max_length=225)),
                ('to', models.CharField(max_length=225)),
                ('calculation_per_year', models.CharField(max_length=225)),
                ('pay_head_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.create_payhead')),
            ],
        ),
        migrations.CreateModel(
            name='E_found_trasfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acount_No', models.CharField(max_length=225)),
                ('IFSC_code', models.CharField(max_length=225)),
                ('Bank_name', models.CharField(max_length=225)),
                ('Cheque', models.CharField(max_length=225)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='compute_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compute', models.CharField(default='Null', max_length=225)),
                ('effective_from', models.CharField(default='NULL', max_length=225)),
                ('amount_greater', models.CharField(default='NULL', max_length=225)),
                ('amount_upto', models.CharField(default='NULL', max_length=225)),
                ('slab_type', models.CharField(default='NULL', max_length=225)),
                ('value', models.CharField(default='NULL', max_length=225)),
                ('Pay_head_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.create_payhead')),
            ],
        ),
        migrations.CreateModel(
            name='add_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acount_No', models.CharField(max_length=225)),
                ('IFSC_code', models.CharField(max_length=225)),
                ('Bank_name', models.CharField(max_length=225)),
                ('Branch_name', models.CharField(max_length=225)),
                ('Transaction_type', models.CharField(max_length=225)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
            ],
        ),
    ]
