# Generated by Django 4.0.4 on 2022-09-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_create_attendence_create_employeegroup_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uqc',
            new_name='unitQuantityCode',
        ),
    ]
