# Generated by Django 4.0.4 on 2022-09-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_bank3_create_attendence1_create_payhead1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost_centre',
            old_name='cname',
            new_name='c_name',
        ),
    ]
