# Generated by Django 4.0.4 on 2022-09-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_cname_cost_centre_c_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_itemcreation',
            old_name='cost_tracking',
            new_name='expirydate',
        ),
        migrations.AddField(
            model_name='stock_itemcreation',
            name='godown',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock_itemcreation',
            name='trackdate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
