# Generated by Django 4.0.4 on 2022-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_cost_tracking_stock_itemcreation_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='first_unit',
            field=models.CharField(blank=True, default='null', max_length=225),
        ),
        migrations.AlterField(
            model_name='units1',
            name='first_unit',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
