# Generated by Django 4.0.4 on 2022-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_units_first_unit_alter_units1_first_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='units1',
        ),
        migrations.AlterField(
            model_name='units',
            name='first_unit',
            field=models.CharField(max_length=225),
        ),
    ]
