# Generated by Django 4.0.4 on 2022-09-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_units1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units1',
            name='first_unit',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
