# Generated by Django 4.0.4 on 2022-09-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_units1_first_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units1',
            name='first_unit',
            field=models.CharField(max_length=225),
        ),
    ]
