# Generated by Django 4.0.6 on 2022-09-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_units1_first_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='statistics_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accounts_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='statistics_Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vouchers_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='statistics_Voucher_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Particulars', models.CharField(max_length=255)),
                ('Debit_Amount', models.IntegerField(blank=True, default='', null=True)),
                ('Credit_Amount', models.IntegerField(blank=True, default='', null=True)),
                ('Month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.months')),
                ('Voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.statistics_vouchers')),
            ],
        ),
        migrations.CreateModel(
            name='statistics_Voucher_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Voucher', models.IntegerField(blank=True, default='', null=True)),
                ('Month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.months')),
                ('Voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.statistics_vouchers')),
            ],
        ),
        migrations.CreateModel(
            name='statistics_Total_Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(blank=True, default=0, null=True)),
                ('Voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.statistics_vouchers')),
            ],
        ),
        migrations.CreateModel(
            name='statistics_Accounts_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(blank=True, default=0, null=True)),
                ('Accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.statistics_accounts')),
            ],
        ),
    ]
