# Generated by Django 4.0.5 on 2022-09-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_creditreg_debitnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis_view',
            name='particular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock_itemcreation'),
        ),
        migrations.AlterField(
            model_name='purchase_model',
            name='itm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock_itemcreation'),
        ),
        migrations.AlterField(
            model_name='sale_model',
            name='itm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock_itemcreation'),
        ),
        migrations.DeleteModel(
            name='stock_item_crt',
        ),
    ]
