# Generated by Django 4.0.5 on 2022-09-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_analysis_view_particular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcreatemodel',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
    ]
