# Generated by Django 4.0.5 on 2022-09-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_groupanalysismodel_pert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeranalysismodel',
            name='lpert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tally_ledger'),
        ),
        migrations.AlterField(
            model_name='purchaseledgervouchermodel',
            name='ludergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tally_ledger'),
        ),
        migrations.AlterField(
            model_name='salesledgervouchermodel',
            name='ludergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tally_ledger'),
        ),
        migrations.DeleteModel(
            name='ledgercreatemodel',
        ),
    ]
