# Generated by Django 4.0.5 on 2022-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_group_voucher_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_ledger',
            name='opening_blnc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
