# Generated by Django 4.0.5 on 2022-09-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_tally_ledger_opening_blnc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Books_Group_under',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_under_Name', models.CharField(blank=True, default='Null', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='cash_bank_books_Group_Under_closing_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_closing_balance_debit', models.IntegerField(blank=True, default='', null=True)),
                ('total_closing_balance_credit', models.IntegerField(blank=True, default='', null=True)),
                ('group_under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.account_books_group_under')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Books_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(blank=True, default='Null', max_length=225)),
                ('ledger_opening_bal', models.IntegerField(blank=True, default='Null')),
                ('ledger_opening_bal_type', models.CharField(blank=True, default='Null', max_length=225)),
                ('group_under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.account_books_group_under')),
            ],
        ),
    ]
