# Generated by Django 4.0.5 on 2022-09-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_account_books_group_under_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash_bank_books_TotalClosing_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Closing_balance', models.IntegerField(blank=True, default='', null=True)),
                ('type', models.CharField(max_length=225)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.account_books_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='cash_bank_books_Leger_Month_closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closing_balance', models.IntegerField(blank=True, default='', null=True)),
                ('type', models.CharField(max_length=225)),
                ('debit', models.IntegerField(blank=True, default='', null=True)),
                ('credit', models.IntegerField(blank=True, default='', null=True)),
                ('Ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.account_books_ledger')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.months')),
            ],
        ),
        migrations.CreateModel(
            name='Account_books_Ledger_Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Particualrs', models.CharField(max_length=225)),
                ('Vch_Type', models.CharField(max_length=225)),
                ('Vch_No', models.CharField(max_length=225)),
                ('Debit', models.IntegerField(blank=True, default='', null=True)),
                ('Credit', models.IntegerField(blank=True, default='', null=True)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.account_books_ledger')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.months')),
            ],
        ),
    ]
