# Generated by Django 4.0.5 on 2022-09-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_first_voucher_summary_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=40, null=True)),
                ('Debit', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
                ('Group_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_group')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Voucher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular', models.CharField(max_length=30, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Vch_Type', models.CharField(max_length=40, null=True)),
                ('Vch_No', models.IntegerField(default=0, null=True)),
                ('Debit', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
                ('Open_Balance', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Second_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50, null=True)),
                ('Fgroup_Forng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.first_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Third_Group_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=50, null=True)),
                ('Sgroup_Forng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.second_group_summary_model')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Monthly_Summary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Balance', models.IntegerField(default=0, null=True)),
                ('Particular', models.CharField(max_length=30, null=True)),
                ('Dedit', models.IntegerField(default=0, null=True)),
                ('Credit', models.IntegerField(default=0, null=True)),
                ('Closing_Balance', models.IntegerField(default=0, null=True)),
                ('Tgroup_Forgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.third_group_summary_model')),
            ],
        ),
    ]
