# Generated by Django 4.0.4 on 2022-09-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_first_group_summary_model_ledger_voucher_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_vouchermodels',
            name='prvnt_duplictes',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='create_vouchermodels',
            name='use_effective_date',
            field=models.CharField(max_length=225),
        ),
    ]
