# Generated by Django 4.0.4 on 2022-09-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_create_vouchermodels_prvnt_duplictes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_attendence',
            name='period',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='create_attendence',
            name='units',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
