# Generated by Django 4.0.4 on 2022-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_create_attendence_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='uqc1',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
