# Generated by Django 4.0.4 on 2022-09-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_units_uqc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='uqc1',
            field=models.CharField(blank=True, default='ull', max_length=225),
        ),
    ]
