# Generated by Django 4.0.4 on 2022-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_units_uqc1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_group',
            name='status',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
