# Generated by Django 4.0.5 on 2022-09-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_voucher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockgroupcreation',
            name='comp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
            preserve_default=False,
        ),
    ]
