# Generated by Django 4.0.5 on 2022-09-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_rename_comp_stockgroupcreation_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockgroupcreation',
            name='company',
        ),
    ]
