# Generated by Django 4.0.5 on 2022-09-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_stockgroupcreation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_itemcreation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
    ]
