# Generated by Django 4.0.4 on 2022-09-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_stock_itemcreation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_centre',
            name='status',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='create_employeegroup',
            name='status',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='currencyalteration',
            name='status',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
