# Generated by Django 4.0.4 on 2022-09-30 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_create_attendence_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_payhead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
    ]
