# Generated by Django 4.0.4 on 2022-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_create_vouchermodels_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='credit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='debit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='particularsto',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
