# Generated by Django 4.0.4 on 2022-10-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_ininxvouchert'),
    ]

    operations = [
        migrations.CreateModel(
            name='vouchert1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdate', models.DateField()),
                ('particular', models.CharField(max_length=255)),
                ('under', models.CharField(max_length=255, null=True)),
                ('account', models.CharField(max_length=255)),
                ('vouchertype', models.CharField(max_length=255)),
                ('voucherno', models.IntegerField()),
                ('openingbal', models.IntegerField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreation')),
            ],
        ),
    ]
