# Generated by Django 4.0.4 on 2022-10-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_inincvouchert_company_ininxvouchert_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svouchert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivdate', models.DateField()),
                ('iparticular', models.CharField(max_length=255)),
                ('iunder', models.CharField(max_length=255, null=True)),
                ('iaccount', models.CharField(max_length=255)),
                ('ivouchertype', models.CharField(max_length=255)),
                ('ivoucherno', models.IntegerField()),
                ('iopeningbal', models.IntegerField(null=True)),
                ('idebit', models.IntegerField(null=True)),
                ('icredit', models.IntegerField(null=True)),
                ('iledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreation')),
            ],
        ),
        migrations.CreateModel(
            name='Pvouchert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivdate', models.DateField()),
                ('iparticular', models.CharField(max_length=255)),
                ('iunder', models.CharField(max_length=255, null=True)),
                ('iaccount', models.CharField(max_length=255)),
                ('ivouchertype', models.CharField(max_length=255)),
                ('ivoucherno', models.IntegerField()),
                ('iopeningbal', models.IntegerField(null=True)),
                ('idebit', models.IntegerField(null=True)),
                ('icredit', models.IntegerField(null=True)),
                ('iledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreation')),
            ],
        ),
        migrations.CreateModel(
            name='DIvouchert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdate', models.DateField()),
                ('particular', models.CharField(max_length=255)),
                ('under', models.CharField(max_length=255, null=True)),
                ('account', models.CharField(max_length=255)),
                ('vouchertype', models.CharField(max_length=255)),
                ('voucherno', models.IntegerField()),
                ('openingbal', models.IntegerField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreation')),
            ],
        ),
        migrations.CreateModel(
            name='BDvouchert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdate', models.DateField()),
                ('particular', models.CharField(max_length=255)),
                ('under', models.CharField(max_length=255, null=True)),
                ('account', models.CharField(max_length=255)),
                ('vouchertype', models.CharField(max_length=255)),
                ('voucherno', models.IntegerField()),
                ('openingbal', models.IntegerField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreation')),
            ],
        ),
    ]
